_name: null
common:
  _name: null
  no_progress_bar: false
  log_interval: 100
  log_format: null
  log_file: bart_base_trainning.log
  aim_repo: null
  aim_run_hash: null
  tensorboard_logdir: bart_base_logs
  wandb_project: null
  azureml_logging: false
  seed: 1
  cpu: false
  tpu: false
  bf16: false
  memory_efficient_bf16: false
  fp16: true
  memory_efficient_fp16: false
  fp16_no_flatten_grads: false
  fp16_init_scale: 128
  fp16_scale_window: null
  fp16_scale_tolerance: 0.0
  on_cpu_convert_precision: false
  min_loss_scale: 0.0001
  threshold_loss_scale: null
  amp: false
  amp_batch_retries: 2
  amp_init_scale: 128
  amp_scale_window: null
  user_dir: null
  empty_cache_freq: 0
  all_gather_list_size: 16384
  model_parallel_size: 1
  quantization_config_path: null
  profile: false
  reset_logging: false
  suppress_crashes: false
  use_plasma_view: false
  plasma_path: /tmp/plasma
common_eval:
  _name: null
  path: null
  post_process: null
  quiet: false
  model_overrides: '{}'
  results_path: null
distributed_training:
  _name: null
  distributed_world_size: 1
  distributed_num_procs: 1
  distributed_rank: 0
  distributed_backend: nccl
  distributed_init_method: null
  distributed_port: -1
  device_id: 0
  distributed_no_spawn: false
  ddp_backend: pytorch_ddp
  ddp_comm_hook: none
  bucket_cap_mb: 25
  fix_batches_to_gpus: false
  find_unused_parameters: true
  gradient_as_bucket_view: false
  fast_stat_sync: false
  heartbeat_timeout: -1
  broadcast_buffers: false
  slowmo_momentum: null
  slowmo_base_algorithm: localsgd
  localsgd_frequency: 3
  nprocs_per_node: 1
  pipeline_model_parallel: false
  pipeline_balance: null
  pipeline_devices: null
  pipeline_chunks: 0
  pipeline_encoder_balance: null
  pipeline_encoder_devices: null
  pipeline_decoder_balance: null
  pipeline_decoder_devices: null
  pipeline_checkpoint: never
  zero_sharding: none
  fp16: true
  memory_efficient_fp16: false
  tpu: false
  no_reshard_after_forward: false
  fp32_reduce_scatter: false
  cpu_offload: false
  use_sharded_state: false
  not_fsdp_flatten_parameters: false
dataset:
  _name: null
  num_workers: 4
  skip_invalid_size_inputs_valid_test: true
  max_tokens: 4096
  batch_size: null
  required_batch_size_multiple: 1
  required_seq_len_multiple: 1
  dataset_impl: null
  data_buffer_size: 10
  train_subset: train
  valid_subset: valid
  combine_valid_subsets: null
  ignore_unused_valid_subsets: false
  validate_interval: 1
  validate_interval_updates: 0
  validate_after_updates: 0
  fixed_validation_seed: null
  disable_validation: false
  max_tokens_valid: 4096
  batch_size_valid: null
  max_valid_steps: null
  curriculum: 0
  gen_subset: test
  num_shards: 1
  shard_id: 0
  grouped_shuffling: false
  update_epoch_batch_itr: false
  update_ordered_indices_seed: false
optimization:
  _name: null
  max_epoch: 20
  max_update: 0
  stop_time_hours: 0.0
  clip_norm: 0.1
  sentence_avg: false
  update_freq:
  - 4
  lr:
  - 3.0e-05
  stop_min_lr: -1.0
  use_bmuf: false
  skip_remainder_batch: false
  debug_param_names: false
checkpoint:
  _name: null
  save_dir: checkpoints/bart_base
  restore_file: checkpoint_last.pt
  continue_once: null
  finetune_from_model: null
  reset_dataloader: true
  reset_lr_scheduler: false
  reset_meters: true
  reset_optimizer: true
  optimizer_overrides: '{}'
  save_interval: 1
  save_interval_updates: 0
  keep_interval_updates: -1
  keep_interval_updates_pattern: -1
  keep_last_epochs: 2
  keep_best_checkpoints: -1
  no_save: false
  no_epoch_checkpoints: false
  no_last_checkpoints: false
  no_save_optimizer_state: false
  best_checkpoint_metric: loss
  maximize_best_checkpoint_metric: false
  patience: -1
  checkpoint_suffix: ''
  checkpoint_shard_count: 1
  load_checkpoint_on_all_dp_ranks: false
  write_checkpoints_asynchronously: false
  model_parallel_size: 1
bmuf:
  _name: null
  block_lr: 1.0
  block_momentum: 0.875
  global_sync_iter: 50
  warmup_iterations: 500
  use_nbm: false
  average_sync: false
  distributed_world_size: 1
generation:
  _name: null
  beam: 5
  beam_mt: 0
  nbest: 1
  max_len_a: 0.0
  max_len_b: 200
  max_len_a_mt: 0.0
  max_len_b_mt: 200
  min_len: 1
  match_source_len: false
  unnormalized: false
  no_early_stop: false
  no_beamable_mm: false
  lenpen: 1.0
  lenpen_mt: 1.0
  unkpen: 0.0
  replace_unk: null
  sacrebleu: false
  score_reference: false
  prefix_size: 0
  no_repeat_ngram_size: 0
  sampling: false
  sampling_topk: -1
  sampling_topp: -1.0
  constraints: null
  temperature: 1.0
  diverse_beam_groups: -1
  diverse_beam_strength: 0.5
  diversity_rate: -1.0
  print_alignment: null
  print_step: false
  lm_path: null
  lm_weight: 0.0
  iter_decode_eos_penalty: 0.0
  iter_decode_max_iter: 10
  iter_decode_force_max_iter: false
  iter_decode_with_beam: 1
  iter_decode_with_external_reranker: false
  retain_iter_history: false
  retain_dropout: false
  retain_dropout_modules: null
  decoding_format: null
  no_seed_provided: false
  eos_token: null
eval_lm:
  _name: null
  output_word_probs: false
  output_word_stats: false
  context_window: 0
  softmax_batch: 9223372036854775807
interactive:
  _name: null
  buffer_size: 0
  input: '-'
model:
  no_progress_bar: false
  log_interval: 100
  log_format: null
  log_file: bart_base_trainning.log
  aim_repo: null
  aim_run_hash: null
  tensorboard_logdir: bart_base_logs
  wandb_project: null
  azureml_logging: false
  seed: 1
  cpu: false
  tpu: false
  bf16: false
  memory_efficient_bf16: false
  fp16: true
  memory_efficient_fp16: false
  fp16_no_flatten_grads: false
  fp16_init_scale: 128
  fp16_scale_window: null
  fp16_scale_tolerance: 0.0
  on_cpu_convert_precision: false
  min_loss_scale: 0.0001
  threshold_loss_scale: null
  amp: false
  amp_batch_retries: 2
  amp_init_scale: 128
  amp_scale_window: null
  user_dir: null
  empty_cache_freq: 0
  all_gather_list_size: 16384
  model_parallel_size: 1
  quantization_config_path: null
  profile: false
  reset_logging: false
  suppress_crashes: false
  use_plasma_view: false
  plasma_path: /tmp/plasma
  criterion: label_smoothed_cross_entropy
  tokenizer: null
  bpe: null
  optimizer: adam
  lr_scheduler: polynomial_decay
  simul_type: null
  scoring: bleu
  task: translation
  num_workers: 1
  skip_invalid_size_inputs_valid_test: true
  max_tokens: 2048
  batch_size: null
  required_batch_size_multiple: 1
  required_seq_len_multiple: 1
  dataset_impl: null
  data_buffer_size: 10
  train_subset: train
  valid_subset: valid
  combine_valid_subsets: null
  ignore_unused_valid_subsets: false
  validate_interval: 1
  validate_interval_updates: 0
  validate_after_updates: 0
  fixed_validation_seed: null
  disable_validation: false
  max_tokens_valid: 2048
  batch_size_valid: null
  max_valid_steps: null
  curriculum: 0
  gen_subset: test
  num_shards: 1
  shard_id: 0
  grouped_shuffling: false
  update_epoch_batch_itr: false
  update_ordered_indices_seed: false
  distributed_world_size: 1
  distributed_num_procs: 1
  distributed_rank: 0
  distributed_backend: nccl
  distributed_init_method: null
  distributed_port: -1
  device_id: 0
  distributed_no_spawn: false
  ddp_backend: pytorch_ddp
  ddp_comm_hook: none
  bucket_cap_mb: 25
  fix_batches_to_gpus: false
  find_unused_parameters: true
  gradient_as_bucket_view: false
  fast_stat_sync: false
  heartbeat_timeout: -1
  broadcast_buffers: false
  slowmo_momentum: null
  slowmo_base_algorithm: localsgd
  localsgd_frequency: 3
  nprocs_per_node: 1
  pipeline_model_parallel: false
  pipeline_balance: null
  pipeline_devices: null
  pipeline_chunks: 0
  pipeline_encoder_balance: null
  pipeline_encoder_devices: null
  pipeline_decoder_balance: null
  pipeline_decoder_devices: null
  pipeline_checkpoint: never
  zero_sharding: none
  no_reshard_after_forward: false
  fp32_reduce_scatter: false
  cpu_offload: false
  use_sharded_state: false
  not_fsdp_flatten_parameters: false
  arch: bart_base
  max_epoch: 0
  max_update: 0
  stop_time_hours: 0
  clip_norm: 0.1
  sentence_avg: false
  update_freq:
  - 4
  lr:
  - 3.0e-05
  stop_min_lr: -1.0
  use_bmuf: false
  skip_remainder_batch: false
  debug_param_names: false
  save_dir: checkpoints/bart_base
  restore_file: checkpoint_last.pt
  continue_once: null
  finetune_from_model: null
  reset_dataloader: true
  reset_lr_scheduler: false
  reset_meters: true
  reset_optimizer: true
  optimizer_overrides: '{}'
  save_interval: 1
  save_interval_updates: 0
  keep_interval_updates: -1
  keep_interval_updates_pattern: -1
  keep_last_epochs: 2
  keep_best_checkpoints: -1
  no_save: false
  no_epoch_checkpoints: false
  no_last_checkpoints: false
  no_save_optimizer_state: false
  best_checkpoint_metric: loss
  maximize_best_checkpoint_metric: false
  patience: -1
  checkpoint_suffix: ''
  checkpoint_shard_count: 1
  load_checkpoint_on_all_dp_ranks: false
  write_checkpoints_asynchronously: false
  store_ema: false
  ema_decay: 0.9999
  ema_start_update: 0
  ema_seed_model: null
  ema_update_freq: 1
  ema_fp32: false
  data: /var/tmp/
  source_lang: en
  target_lang: zh
  load_alignments: false
  left_pad_source: true
  left_pad_target: false
  upsample_primary: -1
  truncate_source: true
  num_batch_buckets: 0
  eval_bleu: false
  eval_bleu_args: '{}'
  eval_bleu_detok: space
  eval_bleu_detok_args: '{}'
  eval_tokenized_bleu: false
  eval_bleu_remove_bpe: null
  eval_bleu_print_samples: false
  label_smoothing: 0.1
  report_accuracy: false
  ignore_prefix_size: 0
  adam_betas: (0.9, 0.999)
  adam_eps: 1.0e-08
  weight_decay: 0.01
  use_old_adam: false
  fp16_adam_stats: false
  warmup_updates: 500
  force_anneal: null
  end_learning_rate: 0.0
  power: 1.0
  total_num_update: '20000'
  pad: 1
  eos: 2
  unk: 3
  layernorm_embedding: true
  dropout: 0.1
  attention_dropout: 0.1
  no_seed_provided: false
  encoder_embed_dim: 768
  encoder_ffn_embed_dim: 3072
  encoder_layers: 6
  encoder_attention_heads: 12
  decoder_layers: 6
  decoder_attention_heads: 12
  encoder_embed_path: null
  encoder_normalize_before: false
  encoder_learned_pos: true
  decoder_embed_path: null
  decoder_embed_dim: 768
  decoder_ffn_embed_dim: 3072
  decoder_normalize_before: false
  decoder_learned_pos: true
  relu_dropout: 0.0
  max_target_positions: 1024
  max_source_positions: 1024
  adaptive_softmax_cutoff: null
  adaptive_softmax_dropout: 0
  share_decoder_input_output_embed: true
  share_all_embeddings: false
  decoder_output_dim: 768
  decoder_input_dim: 768
  no_scale_embedding: true
  activation_fn: gelu
  pooler_activation_fn: tanh
  pooler_dropout: 0.0
  _name: bart_base
  activation_dropout: 0.0
  merge_src_tgt_embed: false
  no_token_positional_embeddings: false
  adaptive_input: false
  no_cross_attention: false
  cross_self_attention: false
  tie_adaptive_weights: false
  checkpoint_activations: false
  offload_activations: false
  encoder_layers_to_keep: null
  decoder_layers_to_keep: null
  encoder_layerdrop: 0
  decoder_layerdrop: 0
  quant_noise_pq: 0
  quant_noise_pq_block_size: 8
  quant_noise_scalar: 0
  min_params_to_wrap: 100000000
task:
  _name: translation
  data: /var/tmp/
  source_lang: en
  target_lang: zh
  load_alignments: false
  left_pad_source: true
  left_pad_target: false
  max_source_positions: 1024
  max_target_positions: 1024
  upsample_primary: -1
  truncate_source: true
  num_batch_buckets: 0
  train_subset: train
  dataset_impl: null
  required_seq_len_multiple: 1
  eval_bleu: false
  eval_bleu_args: '{}'
  eval_bleu_detok: space
  eval_bleu_detok_args: '{}'
  eval_tokenized_bleu: false
  eval_bleu_remove_bpe: null
  eval_bleu_print_samples: false
criterion:
  _name: label_smoothed_cross_entropy
  label_smoothing: 0.1
  report_accuracy: false
  ignore_prefix_size: 0
  sentence_avg: false
optimizer:
  _name: adam
  adam_betas: (0.9, 0.999)
  adam_eps: 1.0e-08
  weight_decay: 0.01
  use_old_adam: false
  fp16_adam_stats: false
  tpu: false
  lr:
  - 3.0e-05
lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 500
  force_anneal: null
  end_learning_rate: 0.0
  power: 1.0
  total_num_update: 20000.0
  lr:
  - 3.0e-05
scoring:
  _name: bleu
  pad: 1
  eos: 2
  unk: 3
bpe: null
tokenizer: null
ema:
  _name: null
  store_ema: false
  ema_decay: 0.9999
  ema_start_update: 0
  ema_seed_model: null
  ema_update_freq: 1
  ema_fp32: false
simul_type: null
task_class: TranslationTask
model_class: BARTModel
criterion_class: LabelSmoothedCrossEntropyCriterion
